# Generated by Django 5.1.3 on 2024-11-23 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_booking_first_name_booking_reservation_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='first_name',
        ),
        migrations.AlterField(
            model_name='booking',
            name='customer_name',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
    ]
